include ../defines.mk

TEST_NAME = histogram
TEST_FILES = histogram
TEST_ARGS = $(DATASET_HOME)/histogram/large.bmp $(NCORES)

CFLAGS = -DREPEAT=500
#CFLAGS += -DNO_FALSE_SHARING


include $(HOME)/Default.mk

